### ISSUE TITLE
[Bug] Resource Type in Reference Changed to Parent's Resource Type

### ISSUE THREAD

**Issue by nathan-abacus** [awslabs/fhir-works-on-aws-routing#96] opened 2021-06-16 20:16 UTC
**Describe the bug**
When a resource (in a bundle) with a reference that has a real id is saved to dynamodb, the resource type in the reference is replaced with the parent resource type. e.g. an EOB has a reference for Coverage with real id Coverage/195a13d1-2fdc-4c26-9fed-14993cffee6b. when the EOB is saved to ddb, the reference for the Coverage becomes ExplanationOfBenefit/195a13d1-2fdc-4c26-9fed-14993cffee6b

**To Reproduce**
1. create a resource with a reference that has a real id
2. save the resource through DynamoDbBundleService.transaction()

**Expected behavior**
the reference with a real id should not be changed

**Comment by nathan-abacus** [comment] 2021-06-16 20:18
Looks like there is an issue in bundleParser.js:
   ` let fullUrl = `${rootUrl}${resourceType}/${id}`;`
when `rootUrl` is undefined, the fullUrl becomes something like `undefinedCoverage/195a13d1-2fdc-4c26-9fed-14993cffee6b.`

**Comment by rsmayda** [comment] 2021-06-17 15:36
Thank you Nathan! Just to confirm what version of the Router are you using? To check look at your [package.json](https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/package.json#L3)

**Comment by nathan-abacus** [comment] 2021-06-17 19:39
Hi Robert,

We are using fhir-works-on-aws-routing@5.4.1

Thank you,
Nathan

**Comment by ssvegaraju** [comment] 2021-07-06 16:25
Hi Nathan. Thanks again for alerting us to this issue, however we weren't able to reproduce. I will close this for now, but do check out [this issue](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/305) that seems to be a similar error that is already fixed, or provide a `bundle.json` to repro the bug. If you have further issues feel free to reopen!

**Closed as completed by ssvegaraju** 2021-07-06 16:25 UTC
Labels: bug
