### ISSUE TITLE
[Bug] Aegis Touchstone Validation Errors on CapabilityStatement with IGs

### ISSUE THREAD

**Issue by Nathan-acoustic** [awslabs/fhir-works-on-aws-routing#123] opened 2021-09-01 14:15 UTC
CapabilityStatement retrieved by 'metadataRoute' has these similar validation errors:

![image](https://user-images.githubusercontent.com/70229685/131687236-60e15bec-9c4b-49d2-83f3-62f263c2b968.png)

![image](https://user-images.githubusercontent.com/70229685/131687316-dc0d5061-f75b-4a8d-a756-e3077ba20ec5.png)

![image](https://user-images.githubusercontent.com/70229685/131687381-f84a45a1-2c98-4ba0-acec-7048b0f89c64.png)

**Comment by Nathan-acoustic** [comment] 2021-09-01 14:20
@carvantes @rsmayda Thank you for fixing #106. Can you take a look at this one?

**Comment by rsmayda** [comment] 2021-09-01 14:58
Hey Nathan thanks for reaching out, Could you confirm:
* Version of router you are using?
* What IGs you have installed?

**Comment by Nathan-acoustic** [comment] 2021-09-03 16:16
@rsmayda we are using:

`fhir-works-on-aws-routing.git#v5.4.4`

```
"hl7.fhir.r4.core": "4.0.1",
"hl7.fhir.us.carin-bb": "1.0.0",
"hl7.fhir.us.davinci-pdex": "1.0.0",
"hl7.fhir.us.davinci-pdex-plan-net": "1.0.0",
"hl7.fhir.us.Davinci-drug-formulary": "1.0.1"
```

**Comment by Nathan-acoustic** [comment] 2021-09-03 16:21
The test is done on Aegis Touchstone

**Comment by rsmayda** [comment] 2021-10-08 17:52
I have added this to our backlog!

**Comment by ssvegaraju** [comment] 2021-11-26 00:19
Hi @Nathan-acoustic, I set up a Touchstone test with the provided implementation guides, and was able to pass the tests. Further, searching through the CapabilityStatement retrieved from the `/metadata` endpoint showed the correct `supportedProfiles` lists for the resources listed in the above screenshots. As I was unable to reproduce, I'm going to go ahead and close this issue, but feel free to reopen if there's anything else!

**Closed as completed by ssvegaraju** 2021-11-26 00:19 UTC
Labels: bug
